<?php
$contests = getContests();
?>

    <h1><?php echo $this->getTitles(); ?></h1>
    <?php echo $contests; ?>


<?php
function getContests()
{
    $contests = Mage::getModel('softuni_contest/contest')->getCollection()
        ->addFieldToSelect(array('title'))
        ->addFieldToFilter('is_active', 1)
        ->load();

    if ( !count($contests->getData()) )
    {
        $out = "No active contests found";
    }
    foreach ($contests->getData() as $val)
    {
        $out.="<h3><a href=\"softuni_contest/form/enter/cid/".$val['contest_id']."\">".$val['title']."</a></h3>";
    }

    return $out;

}

?>